hydra:
  job:
    chdir: false
log_wandb: false
data_set: "airbnb"
feat_type: "vit"
calculate_stuff: false
submod_function: "facility_location"
distance_metric: "euclidean"
similarity_kernel: "gaussian"
compute_random_stats: false
use_sml: true
use_gpu: false