hydra:
  job:
    chdir: false
log_wandb: false
data_set: "20newsgroups"
feat_type: "sbert"
submod_function: "disparity_min"
distance_metric: "arbitrary"
similarity_kernel: "cosine"
compute_random_stats: false
use_sml: true
use_gpu: false